# Generated by Django 4.0.4 on 2022-06-08 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semilleros', '0005_rename_g_in_semillero_g_investigacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ni', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, verbose_name='NOMBRE COMPLETO')),
                ('fecha_n', models.CharField(max_length=250, verbose_name='FECHA DE NACIMIENTO')),
                ('direccion', models.CharField(max_length=250, verbose_name='DIRECCIÓN RESIDENCIA')),
                ('email', models.EmailField(max_length=250, verbose_name='CORREO ELECTRÓNICO')),
                ('l_espedicion', models.CharField(max_length=250, verbose_name='LUGAR DE EXPEDICIÓN ID')),
                ('l_nacimiento', models.CharField(max_length=250, verbose_name='LUGAR DE NACIMIENTO')),
                ('telefono', models.BigIntegerField(verbose_name='TELÉFONO/ CELULAR')),
                ('n_emergencia', models.CharField(max_length=250, verbose_name='EN CASO DE EMERGENCIA LLAMAR A')),
                ('numero_emergencia', models.CharField(max_length=250, verbose_name='NÚMERO DE CONTACTO')),
                ('activo', models.BooleanField(default=False, verbose_name='ACTIVO')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('id_semillero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_semillero', to='semilleros.semillero')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=250, verbose_name='Programa')),
                ('año_i', models.CharField(max_length=250, verbose_name='AÑO INGRESO')),
                ('semestre_a', models.CharField(max_length=250, verbose_name='SEMESTRE ACTUAL')),
                ('f_grado', models.CharField(max_length=250, verbose_name='FECHA DE GRADO')),
                ('pregrado', models.CharField(max_length=250, verbose_name='PREGRADO')),
                ('posgrado', models.CharField(max_length=250, verbose_name='POSGRADOS')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_3', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_2', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lengua', models.CharField(max_length=250, verbose_name='LENGUA')),
                ('nivel', models.CharField(max_length=250, verbose_name='NIVEL')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_1', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematica', models.CharField(max_length=250, verbose_name='TEMATICA')),
                ('institucion', models.CharField(max_length=250, verbose_name='INSTITUCION')),
                ('t_vinculacion', models.CharField(max_length=250, verbose_name='TIPO DE VINCULACION')),
                ('año', models.CharField(max_length=250, verbose_name='AÑO')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_4', to='usuarios.usuario')),
            ],
        ),
    ]
