# Generated by Django 4.0.4 on 2022-06-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_semillero',
        ),
        migrations.AlterField(
            model_name='curso',
            name='año',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='AÑO'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='institucion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='INSTITUCION'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='t_vinculacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='TIPO DE VINCULACION'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tematica',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='TEMATICA'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='lengua',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='LENGUA'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nivel',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='NIVEL'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='año_i',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='AÑO INGRESO'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='f_grado',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FECHA DE GRADO'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='posgrado',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='POSGRADOS'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='pregrado',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PREGRADO'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='programa',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='semestre_a',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='SEMESTRE ACTUAL'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='ACTIVO'),
        ),
    ]
