# Generated by Django 4.0.4 on 2022-06-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0007_remove_semillero_id_usuario'),
        ('usuarios', '0002_remove_usuario_id_semillero_alter_curso_año_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_semillero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='semilerolist', to='semilleros.semillero'),
            preserve_default=False,
        ),
    ]
