# Generated by Django 4.0.4 on 2022-06-09 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0007_remove_semillero_id_usuario'),
        ('usuarios', '0003_usuario_id_semillero'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='rol',
            field=models.CharField(default=None, max_length=250, verbose_name='Rol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_semillero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioslist', to='semilleros.semillero'),
        ),
    ]
