# Generated by Django 4.0.4 on 2022-06-09 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rol_rol_alter_usuario_id_semillero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rol_c', to='usuarios.rol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Rol'),
        ),
    ]
