# Generated by Django 4.0.4 on 2022-06-09 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_rol_id_usuario_usuario_rol_alter_rol_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='rol',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_3', to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idioma',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idioma_u', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(default=None, max_length=250, verbose_name='Rol'),
            preserve_default=False,
        ),
    ]
