# Generated by Django 4.0.4 on 2022-06-09 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuario_rol_rol_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='año_i',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='f_grado',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='posgrado',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='pregrado',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='semestre_a',
        ),
        migrations.AddField(
            model_name='usuario',
            name='año_i',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='AÑO INGRESO'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='f_grado',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FECHA DE GRADO'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='posgrado',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='POSGRADOS'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pregrado',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PREGRADO'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='programa',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='semestre_a',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='SEMESTRE ACTUAL'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='usuarios.usuario'),
        ),
    ]
