# Generated by Django 4.0.4 on 2022-06-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0007_remove_semillero_id_usuario'),
        ('usuarios', '0007_remove_rol_año_i_remove_rol_f_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lider',
            name='id_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_2', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_semillero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='semilleros.semillero'),
        ),
    ]
