# Generated by Django 4.0.4 on 2022-06-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_lider_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobacion'),
        ),
    ]
