# Generated by Django 4.0.4 on 2022-06-08 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semilleros', '0006_semillero_id_usuario'),
        ('usuarios', '0002_remove_usuario_id_semillero_alter_curso_año_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_s', models.TextField(verbose_name='OBSERVACION S')),
                ('observaciones_u', models.TextField(verbose_name='OBSERVACION U')),
                ('firma_d', models.CharField(max_length=250, verbose_name='DECANO /COMITÉ DE INV. DE LA FACULTAD')),
                ('firma_v', models.CharField(max_length=250, verbose_name='VICERRECTOR DE INVESTIGACIONES U HOMÓLOGO EN SEDE')),
                ('firma_c', models.CharField(max_length=250, verbose_name='DOCENTE COORDINADOR DEL SEMILLERO')),
                ('firma_r', models.CharField(max_length=250, verbose_name='Firma Recibido')),
                ('activo', models.BooleanField(default=False, verbose_name='ACTIVO')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('id_semillero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_semillero_1', to='semilleros.semillero')),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario', to='usuarios.usuario')),
            ],
        ),
    ]
