# Generated by Django 4.0.4 on 2022-06-08 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0006_semillero_id_usuario'),
        ('usuarios', '0002_remove_usuario_id_semillero_alter_curso_año_and_more'),
        ('avals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aval',
            name='firma_c',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='DOCENTE COORDINADOR DEL SEMILLERO'),
        ),
        migrations.AlterField(
            model_name='aval',
            name='firma_d',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='DECANO /COMITÉ DE INV. DE LA FACULTAD'),
        ),
        migrations.AlterField(
            model_name='aval',
            name='firma_r',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Firma Recibido'),
        ),
        migrations.AlterField(
            model_name='aval',
            name='firma_v',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='VICERRECTOR DE INVESTIGACIONES U HOMÓLOGO EN SEDE'),
        ),
        migrations.AlterField(
            model_name='aval',
            name='id_semillero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_semillero_1', to='semilleros.semillero'),
        ),
        migrations.AlterField(
            model_name='aval',
            name='id_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='aval',
            name='observaciones_s',
            field=models.TextField(blank=True, null=True, verbose_name='OBSERVACION S'),
        ),
        migrations.AlterField(
            model_name='aval',
            name='observaciones_u',
            field=models.TextField(blank=True, null=True, verbose_name='OBSERVACION U'),
        ),
    ]
