# Generated by Django 4.0.4 on 2022-06-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0008_semillero_aprobado'),
        ('usuarios', '0011_alter_curso_id_usuario'),
        ('avals', '0005_alter_aval_id_semillero_alter_aval_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aval_semillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobacion')),
                ('activo', models.BooleanField(verbose_name='ACTIVO')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('id_semillero', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprobado_s', to='semilleros.semillero')),
            ],
        ),
        migrations.CreateModel(
            name='Aval_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobacion')),
                ('activo', models.BooleanField(verbose_name='ACTIVO')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprobado_e', to='usuarios.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Aval',
        ),
    ]
