# Generated by Django 4.0.4 on 2022-06-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0002_rename_investigacion_semillero_g_investigacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semillero',
            old_name='l_investigacion_asociado',
            new_name='l_i_asociado',
        ),
        migrations.AlterField(
            model_name='semillero',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='ACTIVO'),
        ),
        migrations.AlterField(
            model_name='semillero',
            name='justificacion',
            field=models.TextField(verbose_name=' JUSTIFICACIÓN DEL SEMILLERO DE INVESTIGACIÓN'),
        ),
    ]
