# Generated by Django 4.0.4 on 2022-06-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0004_rename_g_investigacion_semillero_g_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semillero',
            old_name='g_in',
            new_name='g_investigacion',
        ),
        migrations.RenameField(
            model_name='semillero',
            old_name='l_i_asociado',
            new_name='l_investigacion_asociado',
        ),
        migrations.AlterField(
            model_name='semillero',
            name='programa_academico',
            field=models.CharField(max_length=250, verbose_name='PROGRMA ACADÉMICO'),
        ),
    ]
