# Generated by Django 4.0.4 on 2022-06-08 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_id_semillero_alter_curso_año_and_more'),
        ('semilleros', '0005_rename_g_in_semillero_g_investigacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_5', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
