# Generated by Django 4.0.4 on 2022-06-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0006_semillero_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semillero',
            name='id_usuario',
        ),
    ]
