# Generated by Django 4.0.4 on 2022-06-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0008_semillero_aprobado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semillero',
            name='aprobado',
        ),
    ]
